version: '3.8'

services:
  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "10000:10000/udp"
    volumes:
      - "./src/main/resources/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./src/main/resources/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
      - "./src/main/resources/janus/streams.list:/usr/local/etc/janus/streams.list"
    restart: always
