
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5436/lib
spring.datasource.username=postgres
spring.datasource.password=admin

spring.application.name=library
server.port=8094
server.servlet.context-path=/library

springdoc.api-docs.path = /api
springdoc.swagger-ui.path=/lib
springdoc.swagger-ui.tagsSorter=alpha

spring.jpa.open-in-view=true
spring.thymeleaf.check-template-location=false 
spring.main.allow-circular-references=true

server.error.whitelabel.enabled =false
server.error.path=/error

spring.main.allow-bean-definition-overriding=true

#Show sql from Hibernate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.highlight_sql=true


powershell.script.path=classpath:script.ps1
video.save.directory=src/main/resources/video

#Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.enabled=true



